### ISSUE TITLE
pod install 出错

### ISSUE THREAD

**Issue by TML007** [BearRan/CRAnimation#1]
[!] Invalid `Podfile` file: undefined method `pods_inherit!' for #<Pod::Podfile:0x007fd581a05538>. Updating CocoaPods might fix the issue.

 #  from /Users/sks/CRAnimation/Example/Podfile:9
 #  -------------------------------------------
 #    target 'CRAnimation_Tests' do
 >      pods_inherit! :search_paths
 #  
 #  -------------------------------------------

**Comment by BearRan** [comment]
用pod --version查看pod版本，
你的pod版本是0.3.9的话，会出现这个问题，升级pod到最新版。但是升级可能比较麻烦。
或者使用如下格式修改下podFile
target 'CRAnimation_Example' do
  pod 'CRAnimation',        :path => '../'
  pod 'FLAnimatedImage',    '~> 1.0'
  pod 'YLGIFImage'
end

target 'BearSkillDemoTests' do
  pod 'FBSnapshotTestCase'
end
